version: '3'

networks:
  default:
    name: main
    external: true

services:
  terminal:
    build: .
    container_name: terminal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 200s
      timeout: 200s
      retries: 5
